#!/usr/bin/env python3
"""The garden's marks: check the drawing rules, write the night files, print a tile.

Each mark is drawn once, on paper, in two inks: growth green and the bed's accent. The night
file is derived from the paper file through the tokens, never drawn by hand. The rules live in
.brand/DESIGN.md, section 7.

  python3 scripts/marks.py            write every night file from its paper file
  python3 scripts/marks.py --check    exit 1 if a mark breaks a rule or a night file drifted
  python3 scripts/marks.py tile <bed> [--night]   print the mark on a tile, for favicons
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / ".brand"

# bed -> the token its accent comes from. plotplot's bloom is the brand's own accent.
BEDS = {
    "plotplot": "accent",
    "tend": "tend",
    "tilth": "tilth",
    "petals": "petals",
    "umbel": "umbel",
    "pleach": "pleach",
    "pollen": "pollen",
    "copeca": "copeca",
    "weeder": "weeder",
}
GREEN = "primary"
STROKE = "2"
NIGHT_NOTE = "<!-- generated by scripts/marks.py from the paper file; edit that one -->"


def tokens():
    """Paper and night values of every --pp-* colour, read from tokens.css."""
    css = (BRAND / "tokens.css").read_text()
    root, dark = css.split('[data-theme="dark"]', 1)
    pick = lambda block: dict(re.findall(r"--pp-([a-z0-9-]+):\s*(#[0-9A-Fa-f]{6})", block))
    paper = pick(root)
    night = {**paper, **pick(dark)}
    return paper, night


def paper_path(bed):
    if bed == "plotplot":
        return BRAND / "assets" / "plotplot-mark.svg"
    return BRAND / "products" / bed / "assets" / f"{bed}-mark.svg"


def night_path(bed):
    p = paper_path(bed)
    return p.with_name(p.stem + "-night.svg")


def inks(bed, table):
    return {table[GREEN].upper(), table[BEDS[bed]].upper()}


def to_night(bed, svg, paper, night):
    out = svg
    for name in (GREEN, BEDS[bed]):
        out = re.sub(re.escape(paper[name]), night[name], out, flags=re.I)
    return out.replace("\n", "\n  " + NIGHT_NOTE + "\n", 1)


def problems(bed, svg, paper):
    found = []
    if 'viewBox="0 0 24 24"' not in svg:
        found.append("viewBox is not 0 0 24 24")
    used = {c.upper() for c in re.findall(r"#[0-9A-Fa-f]{6}", svg)}
    extra = used - inks(bed, paper)
    if extra:
        found.append(f"inks outside green and the bed's accent: {', '.join(sorted(extra))}")
    widths = set(re.findall(r'stroke-width="([0-9.]+)"', svg))
    if widths - {STROKE}:
        found.append(f"stroke widths other than {STROKE}: {', '.join(sorted(widths - {STROKE}))}")
    if re.search(r"<rect\b", svg):
        found.append("a tile is baked in; tiles come from `marks.py tile`")
    return found


def tile(bed, night_mode):
    paper, night = tokens()
    svg = paper_path(bed).read_text()
    if night_mode:
        svg = to_night(bed, svg, paper, night)
    inner = re.sub(r"<!--.*?-->", "", svg, flags=re.S)
    inner = re.sub(r"^\s*<svg[^>]*>|</svg>\s*$", "", inner.strip(), flags=re.S).strip()
    ground = (night if night_mode else paper)["bg" if night_mode else "surface"]
    scale = 0.72
    offset = round(12 * (1 - scale), 2)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" role="img" aria-label="{bed}">\n'
        f'  <rect width="24" height="24" rx="5.5" fill="{ground}"/>\n'
        f'  <g transform="translate({offset} {offset}) scale({scale})" fill="none" '
        f'stroke-linecap="round" stroke-linejoin="round">\n    {inner}\n  </g>\n</svg>\n'
    )


def main(argv):
    if argv[:1] == ["tile"] and len(argv) >= 2 and argv[1] in BEDS:
        sys.stdout.write(tile(argv[1], "--night" in argv))
        return 0
    check = argv == ["--check"]
    if argv and not check:
        sys.stderr.write(__doc__)
        return 2
    paper, night = tokens()
    failed = False
    for bed in BEDS:
        src = paper_path(bed)
        if not src.exists():
            print(f"{bed}: missing {src.relative_to(ROOT)}")
            failed = True
            continue
        svg = src.read_text()
        for p in problems(bed, svg, paper):
            print(f"{bed}: {p}")
            failed = True
        want = to_night(bed, svg, paper, night)
        dst = night_path(bed)
        if check:
            if not dst.exists() or dst.read_text() != want:
                print(f"{bed}: {dst.relative_to(ROOT)} is not derived from the paper file; run scripts/marks.py")
                failed = True
        else:
            dst.write_text(want)
    if check and not failed:
        print(f"marks: {len(BEDS)} beds, rules hold, night files derived")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
